[package]
name = "sdw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.7.1"
thiserror = "1.0"
owo-colors = "3"
clap = { version = "4", features = ["derive"] }
